# Generated by Django 6.0.3 on 2026-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='jti',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
